### ISSUE TITLE
TuserController not found

### ISSUE THREAD

**Issue by Bootscreen** [XereoNet/SpaceBukkit#134]
hy,

when i shutdown my server and try to open the user-page i get the following error:
http://img703.imageshack.us/img703/6167/tusercontrollererror.png

The Problem is, when i shutdown the server in the top menü stands benutzer / user with a link to tusers (http://img714.imageshack.us/img714/8184/overviewtusers.png)
but when i start the server there is a point with spieler / players and a link to tplayers.

**Comment by pitkley** [comment]
Hey Bootscreen.

Your issue is not related to the plugin for the server itself, but to the control panel. I guess closing this issue and posting it again over at the [SpaceBukkitPanel repo](https://github.com/SpaceDev/SpaceBukkitPanel) could help! But just to let know, in my installation it is the same!

Best regards,
-Pit

**Comment by Bootscreen** [comment]
Now that you mention it, you're right. but why is the issue link on spacebukkit paage linked to this bugtracker -.-

new issue: https://github.com/SpaceDev/SpaceBukkitPanel/issues/3
